# Generated by Django 5.2.1 on 2025-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_opportunite', models.CharField(max_length=50, unique=True)),
                ('nom_client', models.CharField(max_length=255)),
                ('type_garantie', models.CharField(choices=[('DO', 'DO seule'), ('TRC', 'TRC seule')], max_length=4)),
                ('destination_ouvrage', models.CharField(choices=[('HAB', 'Habitation'), ('HHAB', 'Hors habitation')], max_length=4)),
                ('cout_ouvrage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presence_existant', models.BooleanField(default=False)),
                ('client_vip', models.BooleanField(default=False)),
                ('rcmo', models.BooleanField(default=False)),
                ('date_simulation', models.DateTimeField()),
                ('taux_trc', models.DecimalField(decimal_places=2, help_text='En pourcentage, ex: 2.5 pour 2.5%', max_digits=5)),
                ('taux_do', models.DecimalField(decimal_places=2, help_text='En pourcentage', max_digits=5)),
                ('description_ouvrage', models.TextField(blank=True)),
                ('adresse_chantier', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='documents/pdf/')),
                ('fichier_word', models.FileField(blank=True, null=True, upload_to='documents/word/')),
            ],
        ),
    ]
