# Generated by Django 5.2.1 on 2025-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axa', '0002_devis_delete_opportunite'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='type_travaux',
            field=models.CharField(choices=[('RLE', 'Rénovation légère'), ('RLO', 'Rénovation lourde'), ('ON', 'Ouvrage neuf')], default='RLE', max_length=4),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero_devis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devis',
            name='type_garantie',
            field=models.CharField(choices=[('DO', 'DO'), ('TRC', 'TRC')], max_length=4),
        ),
    ]
