# Generated by Django 5.2.1 on 2025-05-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axa', '0003_devis_type_travaux_alter_devis_numero_devis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='type_travaux',
            field=models.CharField(choices=[('RLE', 'Rénovation légère'), ('RLO', 'Rénovation lourde'), ('ON', 'Ouvrage neuf')], max_length=4),
        ),
    ]
